package com.haichaoaixuexi.railway_system_android.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.haichaoaixuexi.railway_system_android.entity.Equipment;
import com.haichaoaixuexi.railway_system_android.entity.Eq_issue_kind;
import com.haichaoaixuexi.railway_system_android.entity.Task;

import com.haichaoaixuexi.railway_system_android.greendao.EquipmentDao;
import com.haichaoaixuexi.railway_system_android.greendao.Eq_issue_kindDao;
import com.haichaoaixuexi.railway_system_android.greendao.TaskDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig equipmentDaoConfig;
    private final DaoConfig eq_issue_kindDaoConfig;
    private final DaoConfig taskDaoConfig;

    private final EquipmentDao equipmentDao;
    private final Eq_issue_kindDao eq_issue_kindDao;
    private final TaskDao taskDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        equipmentDaoConfig = daoConfigMap.get(EquipmentDao.class).clone();
        equipmentDaoConfig.initIdentityScope(type);

        eq_issue_kindDaoConfig = daoConfigMap.get(Eq_issue_kindDao.class).clone();
        eq_issue_kindDaoConfig.initIdentityScope(type);

        taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        equipmentDao = new EquipmentDao(equipmentDaoConfig, this);
        eq_issue_kindDao = new Eq_issue_kindDao(eq_issue_kindDaoConfig, this);
        taskDao = new TaskDao(taskDaoConfig, this);

        registerDao(Equipment.class, equipmentDao);
        registerDao(Eq_issue_kind.class, eq_issue_kindDao);
        registerDao(Task.class, taskDao);
    }
    
    public void clear() {
        equipmentDaoConfig.clearIdentityScope();
        eq_issue_kindDaoConfig.clearIdentityScope();
        taskDaoConfig.clearIdentityScope();
    }

    public EquipmentDao getEquipmentDao() {
        return equipmentDao;
    }

    public Eq_issue_kindDao getEq_issue_kindDao() {
        return eq_issue_kindDao;
    }

    public TaskDao getTaskDao() {
        return taskDao;
    }

}
